export const colors = {
	COLOR_PRIMARY: "#87bfd7",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};

//  Data for categories filter

export const categories = [
	{
		id: "01",
		category: "Restaurants",
	},
	{
		id: "02",
		category: "Fashion",
	},
	{
		id: "08",
		category: "Beauty",
	},
	{
		id: "03",
		category: "Grocery",
	},
	{
		id: "04",
		category: "Health Services",
	},
	{
		id: "05",
		category: "Banking",
	},
	{
		id: "06",
		category: "Church",
	},
	{
		id: "07",
		category: "Other",
	},
];

export const recipeList = [
	{
		id: "01",
		categoryId: "01",
		name: "16 Prospect Wine Bar",
		city: "Westfield",
		image: require("../assets/images/16Prospect.png"),
		rating: "4.7",
		ingredients: ["Ramp leads up to entrance, good wide entrance"],
		time: "5/5",
		difficulty: "4/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Quirky decor & regular live jazz sessions lend this casual American-Italian bistro a bohemian vibe.",
		interior: ["Slightly crammed, higher wooden seats"],
		parking: ["2 spots in the lot across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "02",
		categoryId: "01",
		name: "1958 Cuban Cuisine",
		city: "Westfield",
		image: require("../assets/images/1958CubanCuisine.png"),
		rating: "4.0",
		ingredients: ["Large step in the front"],
		time: "3/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "03",
		categoryId: "01",
		name: "Addams Tavern",
		city: "Westfield",
		image: require("../assets/images/addams.png"),
		rating: "5.0",
		ingredients: ["All good/only first floor as second floor requires stairs"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"New American plates pair with wine in a fashionable setting for lunch, dinner & weekend brunch.",
		interior: ["Spacious and wheelchair accommodating"],
		parking: ["Trader joe's lot down the street, 12 spots "],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "04",
		categoryId: "01",
		name: "Ahrre's Coffee",
		city: "Westfield",
		image: require("../assets/images/Ahrre.png"),
		rating: "3.7",
		ingredients: ["Not large enough, many steps leading up"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Coffee roastery.",
		interior: ["Crammed Interior"],
		parking: ["Baron's parking lot in the rear"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest outside",
	},
	{
		id: "05",
		categoryId: "01",
		name: "Akai Japanese Sushi",
		city: "Westfield",
		image: require("../assets/images/Akai.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Modern Japanese restaurant serving a wide variety of traditional and innovative Japanese cuisine with a full bar offering martinis, wines and sakes.",
		interior: ["Good Interior, happy to accommodate in seating"],
		parking: ["Lot #7 a block down"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "21",
		categoryId: "01",
		name: "Apricot",
		city: "Westfield",
		image: require("../assets/images/apricot.png"),
		rating: "Pending",
		ingredients: ["Submit on form on home screen"],
		time: "/5",
		difficulty: "/5",
		calories: "/5",
		color: "#006A4E",
		description: "",
		interior: ["Pending"],
		parking: ["Pending"],
		bathroom: "",
		seating: "",
	},
	{
		id: "06",
		categoryId: "01",
		name: "Bovellas Pastry Shoppe",
		city: "Westfield",
		rating: "4.7",
		image: require("../assets/images/Bovellas.png"),
		ingredients: ["Adequate pull-side clearance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Long-standing, mom-&-pop bakeshop offering a range of gourmet, kosher pastries, treats & desserts.",
		interior: ["Slightly crammed interior, seating might be hard for wheelchair"],
		parking: ["Trader joe's lot 12 spots down the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "07",
		categoryId: "01",
		name: "Boxwood Coffee Roasters",
		city: "Westfield",
		image: require("../assets/images/Boxwood.png"),
		rating: "4.7",
		ingredients: ["Wide and accessible entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"A family run coffee roastery providing high quality coffee & tea.",
		interior: ["Wide interior with both high top and accessible seating"],
		parking: ["Trader joe's lot 12 spots in the rear"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "08",
		categoryId: "01",
		name: "Brick Oven",
		city: "Westfield",
		image: require("../assets/images/brickoven.png"),
		rating: "4.7",
		ingredients: ["Good entrance, no steps"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Cozy BYOB restaurant serving up traditional Italian pastas & meats roasted in a wood-burning oven.",
		interior: ["Wide aisles, easy wheelchair maneuverability"],
		parking: ["Quimby st parking no spots, Lot #7 5 spots down Central Ave"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "09",
		categoryId: "01",
		name: "Brunella Coffee & Deli",
		city: "Westfield",
		image: require("../assets/images/brunella.png"),
		rating: "3.3",
		ingredients: ["Has a step in front of the door"],
		time: "3/5",
		difficulty: "4/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Portuguese Coffee & Deli",
		interior: ["Slightly crammed Interior"],
		parking: ["Quimby st parking no spots, Lot #7 5 spots down Central Ave"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "11",
		categoryId: "01",
		name: "Casa di Pizza",
		city: "Westfield",
		image: require("../assets/images/casa.png"),
		rating: "4.7",
		ingredients: ["Good entrance, has a small bathroom"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Casual eatery serving specialty & classic pies, plus Italian pasta, subs & make-your-own salads.",
		interior: ["Slightly crammed Interior with tables close together"],
		parking: ["Quimby St Parking or Lot #2 down Quimby with 5 spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "12",
		categoryId: "01",
		name: "Chez Catherine",
		city: "Westfield",
		image: require("../assets/images/chezcatherine.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Elegant French restaurant offering upmarket à la carte lunches & fixed-price dinners.",
		interior: ["Good Interior, happy to accommodate in seating"],
		parking: ["Lot #2 a block down"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "13",
		categoryId: "01",
		name: "Chipotle",
		city: "Westfield",
		image: require("../assets/images/chipotle.png"),
		rating: "5.0",
		ingredients: ["Good entrance in front and back"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Fast-food chain offering Mexican fare, including design-your-own burritos, tacos & bowls.",
		interior: ["Spacious Interior with both booths and wooden seating"],
		parking: ["Lot #1 behind Chipotle, ~13 spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "14",
		categoryId: "01",
		name: "Chocolate Bar",
		city: "Westfield",
		image: require("../assets/images/Chocolate-bar-westfield.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Gourmet chocolatier.",
		interior: ["Spacious Interior with seating"],
		parking: ["Lot #5 across the street, ~7 spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "15",
		categoryId: "01",
		name: "Chutzpah Kitchen",
		city: "Westfield",
		image: require("../assets/images/images.png"),
		rating: "4.7",
		ingredients: ["Large entrance, good ramp in front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Middle-eastern restaurant",
		interior: ["Spacious Interior with seating"],
		parking: ["Lot #5 across the street, ~7 spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "16",
		categoryId: "01",
		name: "Cinnaholic",
		city: "Westfield",
		image: require("../assets/images/Cinnaholic.png"),
		rating: "3.7",
		ingredients: ["Large step in the front without a ramp"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Bakery serving unique cinnamon rolls",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street, (#2) has about ~7 spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "17",
		categoryId: "01",
		name: "Cold Stone Creamery",
		city: "Westfield",
		image: require("../assets/images/coldstone.png"),
		rating: "4.3",
		ingredients: ["Large entrance, good ramp in front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Ice cream chain offering design-your-own creations hand-mixed on a granite slab, plus shakes & more.",
		interior: ["Spacious Interior"],
		parking: ["Only street parking nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "18",
		categoryId: "01",
		name: "Cosimo",
		city: "Westfield",
		image: require("../assets/images/cosimo.png"),
		rating: "4.7",
		ingredients: ["Good entrance, chairs with no arms"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Long-running restaurant dispatching Italian classics from pizza to pasta in a brick-walled setting.",
		interior: ["Spacious Interior, easy wheelchair maneuverability"],
		parking: ["Trader joe's lot 12 spots around the corner & down the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "19",
		categoryId: "01",
		name: "Di Farina Pizzeria",
		city: "Westfield",
		image: require("../assets/images/difarina.png"),
		rating: "5.0",
		ingredients: ["Good ramped entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Your go-to pizzeria for the most delicious pizza, wraps, pasta, salads, and so much more.",
		interior: ["Spacious Interior, easy wheelchair maneuverability"],
		parking: ["Lot #1 with 7 spots behind"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "20",
		categoryId: "01",
		name: "Farinolio",
		city: "Westfield",
		image: require("../assets/images/farinolio.png"),
		rating: "5.0",
		ingredients: ["Yes, all good with no steps"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Experience the authentic and genuine Tuscan flavor with our schiacciata & other specialties!",
		interior: ["Spacious Interior, easy wheelchair maneuverability"],
		parking: ["Lot #1 with 7 spots behind"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "22",
		categoryId: "01",
		name: "Ferraro's Restaurant",
		city: "Westfield",
		image: require("../assets/images/ferraro.png"),
		rating: "4.0",
		ingredients: ["Open entrance"],
		time: "5/5",
		difficulty: "3/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Neighborhood staple delivering traditional Italian meals in roomy, white-tablecloth surrounds.",
		interior: ["Cramped, hard to move wheelchair"],
		parking: ["Lot #1 a block to the left ~14 spots scattered among sides or #2 a short walk below, ~2 spots towards Elm st"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "23",
		categoryId: "01",
		name: "Flamma Pizza",
		city: "Westfield",
		image: require("../assets/images/flamma.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Fiamma Wood Fired Pizza is a beloved, family friendly and highly-rated pizzeria operating in four locations throughout New Jersey, USA",
		interior: ["Good open seating area"],
		parking: ["Lot #5 across the street, ~7 spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "24",
		categoryId: "01",
		name: "Five Guys",
		city: "Westfield",
		image: require("../assets/images/fiveguys.png"),
		rating: "5.0",
		ingredients: ["Great entrance with pull handles and push bars"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Fast-food chain with made-to-order burgers, fries & hot dogs, plus free peanuts while you wait.",
		interior: ["Accessible seating and spacious Interior"],
		parking: ["Lot across the street 2 spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "25",
		categoryId: "01",
		name: "Fresh Bui",
		city: "Westfield",
		image: require("../assets/images/fresh.png"),
		rating: "4.0",
		ingredients: ["No steps, adequate room for wheelchair"],
		time: "5/5",
		difficulty: "4/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"A place for fresh juices, smoothies, teas, and much more.",
		interior: ["Accessible seating, slight cram interior"],
		parking: ["No accessible parking nearby, street parking outside"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "1000",
		categoryId: "01",
		name: "Fresh and Co",
		city: "Westfield",
		image: require("../assets/images/fresh.png"),
		rating: "Pending",
		ingredients: ["Submit on form on home screen"],
		time: "/5",
		difficulty: "/5",
		calories: "/5",
		color: "#006A4E",
		description: "",
		interior: ["Pending"],
		parking: ["Pending"],
		bathroom: "",
		seating: "",
	},
	{
		id: "26",
		categoryId: "01",
		name: "FroYo",
		city: "Westfield",
		image: require("../assets/images/Froyo.png"),
		rating: "5.0",
		ingredients: ["Adequate entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Frozen yogurt shop.",
		interior: ["Accessible seating with good interior"],
		parking: ["Multiple spots out front"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "27",
		categoryId: "01",
		name: "Hershey's Deli",
		city: "Westfield",
		image: require("../assets/images/hershey.png"),
		rating: "4.7",
		ingredients: ["One door is easily accessible to people in wheelchairs"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"For decades we have been making great subs, grill food and catering for people like you. We are proud of what we do.",
		interior: ["Accessible seating with good interior"],
		parking: ["Train lot across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "28",
		categoryId: "01",
		name: "Hunan Wok III",
		city: "Westfield",
		image: require("../assets/images/hunan.png"),
		rating: "4.7",
		ingredients: ["Wide entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Chinese food for pickup",
		interior: ["Lightly crammed interior"],
		parking: ["Lot right behind"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "29",
		categoryId: "01",
		name: "Inspiration Roll",
		city: "Westfield",
		image: require("../assets/images/inspiration.png"),
		rating: "4.7",
		ingredients: ["Large step in the front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"We are a fast casual restaurant offering ramen, sushi burritos and poke bowls.",
		interior: ["Spacious Interior with high top and low top seating"],
		parking: ["Lot #5 across the street, ~5 spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "30",
		categoryId: "01",
		name: "Jade Garden",
		city: "Westfield",
		image: require("../assets/images/jade.png"),
		rating: "3.7",
		ingredients: ["Large step in the front of entrance"],
		time: "3/5",
		difficulty: "3/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"An array of Chinese classics, from chow fun to spicy tilapia, are dispensed from a small storefront.",
		interior: ["Crammed Interior"],
		parking: ["Multiple accessible spots to the side and behind the business"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "31",
		categoryId: "01",
		name: "James Ward Mansion",
		city: "Westfield",
		image: require("../assets/images/jamesward.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Exquisitely lit, this multi-faceted layout offers stately ambiance, privacy, and comfort, for your prestigious and noble affair.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "35",
		categoryId: "01",
		name: "Limani Seafood Grill",
		city: "Westfield",
		image: require("../assets/images/limani.png"),
		rating: "4.2",
		ingredients: ["Multiple accessible doors with push handles"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Popular restaurant serving Greek seafood & other specialties in casual, cozy quarters.",
		interior: ["Spacious Interior with accessible seating"],
		parking: ["Train lot behind the building, Lot #7 right in front"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "36",
		categoryId: "01",
		name: "Lions Roar",
		city: "Westfield",
		image: require("../assets/images/lions.png"),
		rating: "4.0",
		ingredients: ["Large step in the front of the entrance"],
		time: "3/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"A neighborhood brewery focused on providing refreshing beer in a setting designed to help you escape the 9-5.",
		interior: ["Spacious Interior"],
		parking: ["Lot #6 with ~3 spots down Watterson Street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "37",
		categoryId: "01",
		name: "Manhatten Bagel",
		city: "Westfield",
		image: require("../assets/images/manhattan.png"),
		rating: "5.0",
		ingredients: ["Wide entrance with push handles"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Counter-serve chain specializing in NYC-style bagels & coffee, plus salads, soups & sandwiches.",
		interior: ["Spacious Interior"],
		parking: ["2 spots right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "38",
		categoryId: "01",
		name: "Maya Thai Eatery",
		city: "Westfield",
		image: require("../assets/images/maya.png"),
		rating: "Pending",
		ingredients: ["Submit information with link on home screen!"],
		time: "/5",
		difficulty: "/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Maya Thai Eatery offer the Authentic Thai food.",
		interior: ["Pending"],
		parking: ["2 spots right next to it"],
		bathroom: "",
		seating: "",
	},
	{
		id: "39",
		categoryId: "01",
		name: "Mulberry House",
		city: "Westfield",
		image: require("../assets/images/mulberry.png"),
		rating: "5.0",
		ingredients: ["No steps, adequate room for wheelchair and ramp outside for wheelchair"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Tearoom offering farm-fresh lunch fare & weekend brunch in a Victorian house with a cheery vibe.",
		interior: ["Spacious Interior with Accessible Seating"],
		parking: ["Parking lot(s) around the corner 2 spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "42",
		categoryId: "01",
		name: "NY Korean Barbeque",
		city: "Westfield",
		image: require("../assets/images/korean.png"),
		rating: "4.7",
		ingredients: ["ADA compliant"],
		time: "5/5",
		difficulty: "4/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Picture menu featuring classic Korean small plates, rice & noodle dishes, & soups in a casual space.",
		interior: ["Slightly crammed Interior, seating accessible"],
		parking: ["Lot #5 right behind with ~10 spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "43",
		categoryId: "01",
		name: "Old Havana",
		city: "Westfield",
		image: require("../assets/images/havana.png"),
		rating: "4.0",
		ingredients: ["Small step in the front"],
		time: "4/5",
		difficulty: "4/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Slightly crammed interior, wheelchair accessibility might pose challenges"],
		parking: ["Train lot across the street with many wheelchair spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "44",
		categoryId: "01",
		name: "Ono Bowls",
		city: "Westfield",
		image: require("../assets/images/ono.png"),
		rating: "4.3",
		ingredients: ["Good pull handle entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Real fruit smoothies, made to order juices",
		interior: ["Small but spacious Interior"],
		parking: ["Lot #5 with ~10 spots across Central"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "45",
		categoryId: "01",
		name: "Orgreen Poke",
		city: "Westfield",
		image: require("../assets/images/orgreen.png"),
		rating: "4.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "3/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Health food restaurant.",
		interior: ["Wide space with high-top seating"],
		parking: ["Lot #1 across the street ~3 spots nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "46",
		categoryId: "01",
		name: "Outta hand Pizza",
		city: "Westfield",
		image: require("../assets/images/outta.png"),
		rating: "4.7",
		ingredients: ["Wide entrance with pull handle"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"We're a family owned company located in Westfield, NJ. We have the freshest ingredients and the passion to make the perfect pie.",
		interior: ["Slightly crammed Interior might be hard for wheelchair to navigate"],
		parking: ["Train lot across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "47",
		categoryId: "01",
		name: "Qdoba Mexican Eats",
		city: "Westfield",
		image: require("../assets/images/Qdoba.png"),
		rating: "4.3",
		ingredients: ["Wide entrance with pull handle on both sides"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Simple Mexican counter-serve chain for burritos, tacos & more, including health-oriented options.",
		interior: ["Spacious Interior with accessible seating"],
		parking: ["Lot #7 is the closest lot with wheelchair accessible spots ~6"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "48",
		categoryId: "01",
		name: "Rockn' Joe",
		city: "Westfield",
		image: require("../assets/images/rockn.png"),
		rating: "3.7",
		ingredients: ["Good entrance with pull handle"],
		time: "5/5",
		difficulty: "3/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Rock 'n' roll-themed coffee shop with specialty drinks & a basic food menu with sandwiches & salads.",
		interior: ["Crammed Interior, hard for a wheelchair to move through"],
		parking: ["No accessible parking nearby, have to cross a street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "150",
		categoryId: "01",
		name: "Starbucks",
		city: "Westfield",
		image: require("../assets/images/starbucks.png"),
		rating: "5.0",
		ingredients: ["Entrances are good on both sides, good pull-side clearance and wide doors"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Seattle-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		interior: ["Spacious Interior with both booths, high-top, and low-top seating. Easy path for wheelchairs and people who struggle with movability."],
		parking: ["Lot right next to Starbucks, multiple wheelchair accessible spots right nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "49",
		categoryId: "01",
		name: "Vicki's Diner",
		city: "Westfield",
		image: require("../assets/images/vicki.png"),
		rating: "4.7",
		ingredients: ["Good door with wheelchair miniramp to the left"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"American grub served morning to night in a retro-style diner with chrome accents & cozy booths.",
		interior: ["Good interior with high top and low top seating"],
		parking: ["Lot across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "50",
		categoryId: "01",
		name: "Westfield Diner",
		city: "Westfield",
		image: require("../assets/images/westfield.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Relaxed American diner serving breakfast, burgers & sandwiches in an old-school atmosphere.",
		interior: ["Spacious Interior"],
		parking: ["2 wheelchair accessible spots right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "51",
		categoryId: "01",
		name: "Westfield Seafood",
		city: "Westfield",
		image: require("../assets/images/seafood.png"),
		rating: "4.2",
		ingredients: ["Ramped entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Good Interior, room for wheelchair to move around"],
		parking: ["Train lot right by, ~3 spots right next to Westfield Seafood"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "52",
		categoryId: "02",
		name: "Adlers Jewelers",
		city: "Westfield",
		image: require("../assets/images/Adlers.png"),
		rating: "4.7",
		ingredients: ["Ramp leads up to entrance, good wide entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Time-tested, family-owned store offering jewelry as well as appraisals & repairs. World Renowned Designer Engagement Rings and Wedding Bands. Top Designer Jewelry from around the world.",
		interior: ["Spacious Interior, room for wheelchair to move around jewelry display"],
		parking: ["Public Parking Lot #7 Across the street, 5 wheelchair-accessible spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "53",
		categoryId: "02",
		name: "American Shoe Repair",
		city: "Westfield",
		image: require("../assets/images/american.png"),
		rating: "3.7",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Famous footwear.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "54",
		categoryId: "02",
		name: "Athleta",
		city: "Westfield",
		image: require("../assets/images/Athleta.png"),
		rating: "4.7",
		ingredients: ["Good ramped entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Chain retailer for trendy sportswear & accessories for women, offering gear, swimsuits & more.",
		interior: ["Spacious Interior and Accessible Fitting Room"],
		parking: ["Lot #5 across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "55",
		categoryId: "02",
		name: "Banana Republic",
		city: "Westfield",
		image: require("../assets/images/Banana.png"),
		rating: "5.0",
		ingredients: ["Ramped entrance no issues"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Clothing chain featuring classic, stylish pieces for men & women, plus shoes & accessories.",
		interior: ["Spacious Interior"],
		parking: ["Lot #5 right behind with ~5 spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "57",
		categoryId: "02",
		name: "Best Foot Forward",
		city: "Westfield",
		image: require("../assets/images/best.png"),
		rating: "3.7",
		ingredients: ["Entrance is good"],
		time: "5/5",
		difficulty: "3/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Slightly crammed Interior"],
		parking: ["No accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "58",
		categoryId: "02",
		name: "Beyond Trends",
		city: "Westfield",
		image: require("../assets/images/Beyond.png"),
		rating: "4.3",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "4/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Women's clothing store.",
		interior: ["Slightly crammed interior Interior"],
		parking: ["Train lot (#2) down Elm street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "59",
		categoryId: "02",
		name: "Bridget's Irish Cottages",
		city: "Westfield",
		image: require("../assets/images/Bridget.png"),
		rating: "3.3",
		ingredients: ["Wheelchair-accessible entrance"],
		time: "5/5",
		difficulty: "3/5",
		calories: "2/5",
		color: "#006A4E",
		description:
			"Small business * Irish goods store in Westfield, New Jersey",
		interior: ["Cramped Interior"],
		parking: ["No designated accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "60",
		categoryId: "02",
		name: "Claire's",
		city: "Westfield",
		image: require("../assets/images/penis.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "4/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Chain retailer offering an array of jewelry & fashion accessories, plus ear piercing.",
		interior: ["Slightly crammed interior"],
		parking: ["Lot #1 right behind, multiple wheelchair accessible spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "60",
		categoryId: "02",
		name: "Continental Tailoring",
		city: "Westfield",
		image: require("../assets/images/Continental.png"),
		rating: "4.0",
		ingredients: ["Entrance is fine"],
		time: "5/5",
		difficulty: "3/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Local tailor.",
		interior: ["Crammed Interior"],
		parking: ["Lot #3 across the street with many spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "61",
		categoryId: "03",
		name: "Elegant Image",
		city: "Westfield",
		image: require("../assets/images/Elegant.png"),
		rating: "4.7",
		ingredients: ["Ramped entrance in the front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street, multiple wheelchair accessible spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "62",
		categoryId: "02",
		name: "Evalyn Dunn",
		city: "Westfield",
		image: require("../assets/images/Evalyn.png"),
		rating: "5.0",
		ingredients: ["Built to all accessbility standards"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Spacious interior"],
		parking: ["Parking right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "63",
		categoryId: "08",
		name: "Facial Reality Spa",
		city: "Westfield",
		image: require("../assets/images/Facial.png"),
		rating: "4.3",
		ingredients: ["Large step in the front"],
		time: "3/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Beauty spa.",
		interior: ["Spacious Interior"],
		parking: ["Parking right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "64",
		categoryId: "02",
		name: "Flair Cleaners",
		city: "Westfield",
		image: require("../assets/images/Flair.png"),
		rating: "4.0",
		ingredients: ["Two steps in the front"],
		time: "3/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Dry cleaners",
		interior: ["Slightly crammed Interior"],
		parking: ["Train lot across the street, multiple wheelchair accessible spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "65",
		categoryId: "02",
		name: "G O Keller's Inc",
		city: "Westfield",
		image: require("../assets/images/GO.png"),
		rating: "4.3",
		ingredients: ["Large step in the front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Dry cleaners.",
		interior: ["Good Interior"],
		parking: ["PNC bank parking across street, no accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "66",
		categoryId: "02",
		name: "Gap",
		city: "Westfield",
		image: require("../assets/images/Gap.png"),
		rating: "5.0",
		ingredients: ["Good entrance in front and back"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Shop at Gap for casual womens, mens, maternity, kids and baby clothes.",
		interior: ["Spacious Interior with accessible fitting room"],
		parking: ["Lot #4 right behind with multiple accessible spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "67",
		categoryId: "02",
		name: "Glamourous Girlz",
		city: "Westfield",
		image: require("../assets/images/Glamourous.png"),
		rating: "3.3",
		ingredients: ["Stairs in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Glamorousgirlz is a full service salon.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "68",
		categoryId: "02",
		name: "Gordin & Sons",
		city: "Westfield",
		image: require("../assets/images/Gordin.png"),
		rating: "5.0",
		ingredients: ["Yes, easy entrance and high maneuverability"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Preowned watches watch service.",
		interior: ["Spacious Interior"],
		parking: ["Lot #1 right behind"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "69",
		categoryId: "08",
		name: "Guillotine Salon",
		city: "Westfield",
		image: require("../assets/images/Guillotine.png"),
		rating: "3.3",
		ingredients: ["Second floor must access with staircase"],
		time: "1/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Full service salon that is here to meet all of your beauty needs",
		interior: ["Spacious Interior"],
		parking: ["Lot #5 across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "70",
		categoryId: "08",
		name: "Haircut Bar",
		city: "Westfield",
		image: require("../assets/images/Haircut.png"),
		rating: "4.3",
		ingredients: ["Step in the front"],
		time: "3/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Hair salon.",
		interior: ["Spacious Interior"],
		parking: ["Right next to it"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "71",
		categoryId: "02",
		name: "Hope Chest",
		city: "Westfield",
		image: require("../assets/images/Hope.png"),
		rating: "3.3",
		ingredients: ["Small door entrance"],
		time: "4/5",
		difficulty: "3/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"A very cute little shop to find nice trinkets that make great gifts.",
		interior: ["Crammed interior"],
		parking: ["No designated accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "72",
		categoryId: "02",
		name: "Indigo Art Studio",
		city: "Westfield",
		image: require("../assets/images/Indigo.png"),
		rating: "5.0",
		ingredients: ["On second floor, elevator available"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Children's party studio.",
		interior: ["Smaller Interior"],
		parking: ["Lot #4 behind the store"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "73",
		categoryId: "02",
		name: "J. McLaughlin",
		city: "Westfield",
		image: require("../assets/images/J.png"),
		rating: "2.7",
		ingredients: ["Large step in the front"],
		time: "3/5",
		difficulty: "3/5",
		calories: "2/5",
		color: "#006A4E",
		description:
			"Clothing chain stocking classic fashions for men & women, plus accessories such as belts & bags.",
		interior: ["Slightly crammed interior"],
		parking: ["No accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "74",
		categoryId: "02",
		name: "JackRabbit x Fleet Feet",
		city: "Westfield",
		image: require("../assets/images/JackRabbit.png"),
		rating: "5.0",
		ingredients: ["Large door entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Running store.",
		interior: ["Spacious Interior"],
		parking: ["Accessible parking right behind"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "75",
		categoryId: "02",
		name: "John Robert Custom",
		city: "Westfield",
		image: require("../assets/images/John.png"),
		rating: "4.3",
		ingredients: ["Small step in the front of the entrance"],
		time: "4/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Longtime shop providing custom men's shirts, neckties & suits made with English & Italian wools.",
		interior: ["Slightly crammed interior"],
		parking: ["Wheelchair accessible Lot #1 across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "76",
		categoryId: "02",
		name: "Jos A Bank",
		city: "Westfield",
		image: require("../assets/images/Jos.png"),
		rating: "5.0",
		ingredients: ["Wheelchair accessible entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Menswear chain offering house-label suits, dress shirts & pants, plus sportswear & accessories.",
		interior: ["Good wheelchair-accessible Interior"],
		parking: ["Wheelchair accessible Lot #7 right behind"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "77",
		categoryId: "02",
		name: "Jude Connally",
		city: "Westfield",
		image: require("../assets/images/Jude.png"),
		rating: "4.3",
		ingredients: ["Doorknob to enter (can be hard for some with lack of movement)"],
		time: "3/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Women's clothing store",
		interior: ["Slightly crammed interior"],
		parking: ["Lot #5 right behind"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "78",
		categoryId: "08",
		name: "Kennedy's Barber",
		city: "Westfield",
		image: require("../assets/images/Kennedy.png"),
		rating: "4.7",
		ingredients: ["Good spacious door"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Our highly skilled barbers can give you the best traditional or modern cuts",
		interior: ["Spacious Interior"],
		parking: ["Train lot #2 across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "79",
		categoryId: "02",
		name: "Luigino Tailor",
		city: "Westfield",
		image: require("../assets/images/Luigino.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "4/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Tailor",
		interior: ["Slightly small interior"],
		parking: ["Lot #6 nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "80",
		categoryId: "08",
		name: "Luna Grace Beauty",
		city: "Westfield",
		image: require("../assets/images/Luna.png"),
		rating: "3.7",
		ingredients: ["Doorknob handle does not meet ADA standards and step in front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"We are a beauty bar with a spa-like feel located in beautiful downtown Westfield!",
		interior: ["Spacious Interior"],
		parking: ["No accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "81",
		categoryId: "02",
		name: "Madeline Moss",
		city: "Westfield",
		image: require("../assets/images/Madeline.png"),
		rating: "5.0",
		ingredients: ["Pull handles and wide door"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Westfield furniture store.",
		interior: ["Very spacious interior"],
		parking: ["Lot #5 right behind with multiple wheelchair accessible spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "82",
		categoryId: "02",
		name: "Michaelangelo",
		city: "Westfield",
		image: require("../assets/images/Michealangelo.png"),
		rating: "5.0",
		ingredients: ["Good entrance, accommodating to wheelchair users"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Long standing barbershop specializing in children's haircuts.",
		interior: ["Spacious Interior"],
		parking: ["Parking lot #1 right behind it"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "83",
		categoryId: "02",
		name: "Mimi & Hill",
		city: "Westfield",
		image: require("../assets/images/Mimi.png"),
		rating: "4.0",
		ingredients: ["Wide, accessible entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "2/5",
		color: "#006A4E",
		description:
			"A comprehensive approach where a single team manages both the design and construction phases of a project.",
		interior: ["Interior spaced out and built to ADA standards"],
		parking: ["Lot #1 closest lot, still far away"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "84",
		categoryId: "02",
		name: "N&C Jewelers",
		city: "Westfield",
		image: require("../assets/images/N.png"),
		rating: "4.7",
		ingredients: ["No steps, adequate room for wheelchair"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Store owned by Nabig & Carmen, formally of Michael Kohn Jewelers!",
		interior: ["Spacious Interior"],
		parking: ["Lot #5 across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "85",
		categoryId: "08",
		name: "Nails Spa & Beyond",
		city: "Westfield",
		image: require("../assets/images/nails.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Nail salon.",
		interior: ["Very spacious Interior"],
		parking: ["Lot #1 right next to it, many spots for access"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "86",
		categoryId: "03",
		name: "Patricia & Paul",
		city: "Westfield",
		image: require("../assets/images/Patricia.png"),
		rating: "5.0",
		ingredients: ["Accessible entrance, usually kept open"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Shop with the freshest and purest products available.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street, many accessible spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "87",
		categoryId: "08",
		name: "R Studio",
		city: "Westfield",
		image: require("../assets/images/R.png"),
		rating: "4.7",
		ingredients: ["Large step in the front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Salon for eyelash threading",
		interior: ["Spacious Interior"],
		parking: ["Lot #5 across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "88",
		categoryId: "08",
		name: "Salon Peak",
		city: "Westfield",
		image: require("../assets/images/SalonVisage.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"A salon for the best, operated by the best.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street, multiple wheelchair accessible spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "89",
		categoryId: "02",
		name: "Sherwin-Williams",
		city: "Westfield",
		image: require("../assets/images/Sherwin.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Retail location for a painting supplies manufacturer of both interior & exterior products.",
		interior: ["Spacious Interior"],
		parking: ["Train lot across the street, multiple wheelchair accessible spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "90",
		categoryId: "02",
		name: "Starlight Cleaners",
		city: "Westfield",
		image: require("../assets/images/Starlight.png"),
		rating: "5.0",
		ingredients: ["Entrance is fine"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Local dry cleaners",
		interior: ["Spacious Interior"],
		parking: ["Accessible parking right outside"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "91",
		categoryId: "08",
		name: "Supercuts",
		city: "Westfield",
		image: require("../assets/images/Supercuts.png"),
		rating: "5.0",
		ingredients: ["No steps, good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Haircuts for men and women.",
		interior: ["Spacious Interior"],
		parking: ["Accessible parking right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "92",
		categoryId: "02",
		name: "Tamar Jewelery",
		city: "Westfield",
		image: require("../assets/images/Tamar.png"),
		rating: "3.7",
		ingredients: ["Small step in the front, door might be a little small"],
		time: "3/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Small local jeweler",
		interior: ["Spacious Interior"],
		parking: ["No accessible parking nearby"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "94",
		categoryId: "08",
		name: "U Relax Spa",
		city: "Westfield",
		image: require("../assets/images/URelax.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"A very relaxing, clean and quiet environment",
		interior: ["Spacious Interior"],
		parking: ["Accessible parking lots on all sides"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "95",
		categoryId: "02",
		name: "Urban Outfitters",
		city: "Westfield",
		image: require("../assets/images/Urban.png"),
		rating: "4.3",
		ingredients: ["Accessible entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Chain with a hipster vibe known for on-trend fashions, accessories & quirky home-decor items.",
		interior: ["Spacious Interior, elevator to get to separate floors"],
		parking: ["No accessible parking nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "96",
		categoryId: "02",
		name: "Warby Parker",
		city: "Westfield",
		image: require("../assets/images/Warby.png"),
		rating: "4.7",
		ingredients: ["Wide door with pull bars"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warby Parker Inc. is an American retailer of prescription glasses, contact lenses, and sunglasses, based in New York City.",
		interior: ["Spacious Interior"],
		parking: ["Starbucks lot across the street or at&t lot "],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "97",
		categoryId: "02",
		name: "Westfield Tailors",
		city: "Westfield",
		image: require("../assets/images/WestfieldTailors.png"),
		rating: "5.0",
		ingredients: ["Front entrance is good"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Local longstanding tailor",
		interior: ["Spacious Interior"],
		parking: ["Accessible parking right outside"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "99",
		categoryId: "08",
		name: "Wolves Den",
		city: "Westfield",
		image: require("../assets/images/WolvesDen.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Highly-rated local barbershop",
		interior: ["Spacious Interior"],
		parking: ["Lot #7 nearby with many accessible spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "100",
		categoryId: "03",
		name: "Baron's Drug Store",
		city: "Westfield",
		image: require("../assets/images/barons.png"),
		rating: "4.3",
		ingredients: ["Both entrances are good"],
		time: "5/5",
		difficulty: "3/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Baron's Drug Store is a full-service independent pharmacy in Westfield, NJ providing a wide variety of services.",
		interior: ["Cramped aisles, hard to move wheelchair around"],
		parking: ["Handicapped spots right out back"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "102",
		categoryId: "03",
		name: "Trader Joe's",
		city: "Westfield",
		image: require("../assets/images/Trader.png"),
		rating: "5.0",
		ingredients: ["Good entrance with automatic doors"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Grocery chain with a variety of signature items, plus produce, dairy & more (most sell wine & beer).",
		interior: ["Spacious Interior"],
		parking: ["Many wheelchair accessible spots in the lot"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "103",
		categoryId: "03",
		name: "Walgreens",
		city: "Westfield",
		image: require("../assets/images/Walgreens.png"),
		rating: "5.0",
		ingredients: ["Good entrance with automatic wide doors"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Drugstore chain with health & beauty aids, prescriptions & photo services, plus mini-mart basics.",
		interior: ["Spacious Interior"],
		parking: ["multiple handicap spots outside the Walgreens"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "104",
		categoryId: "03",
		name: "Westfield Pharmacy",
		city: "Westfield",
		image: require("../assets/images/Pharmacy.png"),
		rating: "5.0",
		ingredients: ["Very spacious door with pull handles"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Small, newly-opened independent pharmacy",
		interior: ["Spacious Interior"],
		parking: ["Lot #7 with multiple wheelchair accessible spots nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "105",
		categoryId: "03",
		name: "Westfield Seafood",
		city: "Westfield",
		image: require("../assets/images/seafood.png"),
		rating: "4.2",
		ingredients: ["Ramped entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Good Interior, room for wheelchair to move around"],
		parking: ["Train lot right by, ~3 spots right next to Westfield Seafood"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "106",
		categoryId: "04",
		name: "Atlantic Medical",
		city: "Westfield",
		image: require("../assets/images/atlantic.png"),
		rating: "5.0",
		ingredients: ["All good, automatic doors with spacious interior"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Atlantic Health System is a medical group practice located in Westfield, NJ that specializes in Internal Medicine and Family Medicine",
		interior: ["Spacious Interior, easy to move around"],
		parking: ["Accessible parking spots right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "107",
		categoryId: "04",
		name: "Baron's Drug Store",
		city: "Westfield",
		image: require("../assets/images/barons.png"),
		rating: "4.3",
		ingredients: ["Both entrances are good"],
		time: "5/5",
		difficulty: "3/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Baron's Drug Store is a full-service independent pharmacy in Westfield, NJ providing a wide variety of services.",
		interior: ["Cramped aisles"],
		parking: ["Handicapped spots right out back"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "108",
		categoryId: "04",
		name: "Brunner Eye Care",
		city: "Westfield",
		image: require("../assets/images/brunner.png"),
		rating: "4.7",
		ingredients: ["All good, ramped entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Brunner Eye Care is a neighborhood eye care and optical in Westfield, NJ",
		interior: ["Spacious Interior"],
		parking: ["Lot #1 with multiple spots across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "109",
		categoryId: "04",
		name: "Club Pilates",
		city: "Westfield",
		image: require("../assets/images/PilatesC.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"The Pilates classes at Club Pilates offer a strength-training workout for students of any age.",
		interior: ["Spacious Interior"],
		parking: ["Lot #4 right next to the gym"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "110",
		categoryId: "04",
		name: "Dentologem",
		city: "Westfield",
		image: require("../assets/images/Dentologem.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Our dentist is dedicated to providing each patient with quality care and helping them achieve a healthy smile they feel confident in.",
		interior: ["Spacious Interior with wide aisles"],
		parking: ["Lot #3 with multiple spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "111",
		categoryId: "04",
		name: "Green Room",
		city: "Westfield",
		image: require("../assets/images/Green.png"),
		rating: "4.7",
		ingredients: ["Yes, easy entrance and high maneuverability"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Your one stop shop for all of your CBD needs!",
		interior: ["Spacious Interior with low top seating"],
		parking: ["Parking lot #2 down Elm St"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "112",
		categoryId: "04",
		name: "Haven Pelvic PT",
		city: "Westfield",
		image: require("../assets/images/Haven.png"),
		rating: "5.0",
		ingredients: ["Wheelchair ramp for entrance, wide door"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Physical therapy clinic in Westfield.",
		interior: ["Spacious Interior with elevator inside"],
		parking: ["Few parking spaces nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "113",
		categoryId: "04",
		name: "HearingLife",
		city: "Westfield",
		image: require("../assets/images/HearingL.png"),
		rating: "4.7",
		ingredients: ["Good entrance with pull handle"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Discover high-quality hearing aids and professional hearing care at our hearing center located in Westfield, New Jersey.",
		interior: ["Spacious Interior"],
		parking: ["Lot #5 across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "114",
		categoryId: "04",
		name: "I to Eye",
		city: "Westfield",
		image: require("../assets/images/I.png"),
		rating: "5.0",
		ingredients: ["Ramped entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Spacious Interior"],
		parking: ["Lot #4 right behind"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "115",
		categoryId: "04",
		name: "JAG-ONE",
		city: "Westfield",
		image: require("../assets/images/JAG.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"JAG PT Westfield is a multi-specialty physical therapy clinic located on South Avenue West in the heart of downtown Westfield.",
		interior: ["Spacious Interior"],
		parking: ["Spots to the side and across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "116",
		categoryId: "04",
		name: "Laser Dental",
		city: "Westfield",
		image: require("../assets/images/Laser.png"),
		rating: "5.0",
		ingredients: ["Ramped entrance and wide door"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Family-oriented practice specializing in laser dental therapy.",
		interior: ["Wellspaced Interior"],
		parking: ["1 Accessible spot right outside"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "118",
		categoryId: "04",
		name: "Professional PT",
		city: "Westfield",
		image: require("../assets/images/ProfessionalPT.png"),
		rating: "4.7",
		ingredients: ["Good entrance with pull handles"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Professional Physical Therapy in Westfield has been treating patients since 2017 and offers many different types of rehabilitation services to relieve pain.",
		interior: ["Spacious Interior"],
		parking: ["Lot #1 nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "119",
		categoryId: "04",
		name: "Raritan Valley Gyrotonic",
		city: "Westfield",
		image: require("../assets/images/Raritan.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Low-key studio offering group & personal Gyrotonic classes with equipment & Gyrokinesis sessions.",
		interior: ["Good Interior"],
		parking: ["Lot #5 right behind"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "120",
		categoryId: "04",
		name: "Satsang Yoga Studio",
		city: "Westfield",
		image: require("../assets/images/Satsang.png"),
		rating: "3.3",
		ingredients: ["Steep stairs on entrance to reach the studio"],
		time: "1/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Studio offering beginner, flow, prenatal & kids' yoga classes, as well as meditation.",
		interior: ["Spacious Interior"],
		parking: ["Lot #4 right behind"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "121",
		categoryId: "05",
		name: "Bank of America",
		city: "Westfield",
		image: require("../assets/images/BOA.png"),
		rating: "5.0",
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Bank of America financial center is located at 173 Elm St Westfield, NJ 07090.",
		interior: ["Spacious Interior"],
		parking: ["Multiple accessible spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "122",
		categoryId: "05",
		name: "Chase Bank",
		city: "Westfield",
		image: require("../assets/images/Chase.png"),
		rating: "5.0",
		ingredients: ["Ramp to enter from the parking lot"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		interior: ["Spacious Interior"],
		parking: ["1 spot in the back of the bank"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "123",
		categoryId: "05",
		name: "Haven Savings Bank",
		city: "Westfield",
		image: require("../assets/images/bigpenis.png"),
		rating: "5.0",
		ingredients: ["Accessible from the front of the bank"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Full Service Banking That's Hard to Beat. Competitive Fixed and Adjustable Rate Mortgages.",
		interior: ["Spacious Interior"],
		parking: ["2 spots outside the store"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "124",
		categoryId: "05",
		name: "PNC Bank",
		city: "Westfield",
		image: require("../assets/images/PNC.png"),
		rating: "5.0",
		ingredients: ["No steps, adequate room for wheelchair "],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"The Westfield Plaza Branch of PNC Bank is located at 1 LINCOLN PLZ WESTFIELD,NJ 07090.",
		interior: ["Spacious Interior"],
		parking: ["Few spots in nearby parking lot"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "125",
		categoryId: "05",
		name: "Wells Fargo",
		city: "Westfield",
		image: require("../assets/images/Wells.png"),
		rating: "4.3",
		ingredients: ["Good, ramp at back of building"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Committed to the financial health of our customers and communities. Explore bank accounts, loans, mortgages, investing, credit cards & banking services.",
		interior: ["Spacious Interior"],
		parking: ["No accessible parking"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "126",
		categoryId: "06",
		name: "First Baptist Church",
		city: "Westfield",
		image: require("../assets/images/Baptist.png"),
		rating: "5.0",
		ingredients: ["Wheelchair accessible entrance in the back"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"We are sinners saved by God's amazing grace. We have trusted in the risen Jesus and His work on the cross.",
		interior: ["Wheelchair accessible spots in the chapel"],
		parking: ["Wheelchair accessible parking spots"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "127",
		categoryId: "06",
		name: "First Congregational Church",
		city: "Westfield",
		image: require("../assets/images/Congregational.png"),
		rating: "5.0",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"United church of christ",
		interior: ["This church is wheelchair accessible and easy to move around"],
		parking: ["Wheelchair accessible parking spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "128",
		categoryId: "06",
		name: "First United Methodist",
		city: "Westfield",
		image: require("../assets/images/United.png"),
		rating: "5.0",
		ingredients: ["Entrance is ramped and good"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"The United Methodist Church (UMC) is a worldwide mainline Protestant denomination based in the United States, and a major part of Methodism",
		interior: ["Sanctuary on first floor has cutouts for extra room with seating wheelchairs"],
		parking: ["Wheelchair accessible parking spots"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "129",
		categoryId: "07",
		name: "AT&T",
		city: "Westfield",
		image: require("../assets/images/att.png"),
		rating: "4.3",
		ingredients: ["Step in front of it, have to go to the side"],
		time: "4/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Retailer providing wireless plans & a range of phones, devices & accessories.",
		interior: ["Yes widely spaced"],
		parking: ["Multiple wheelchair accessible spots around"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "130",
		categoryId: "07",
		name: "Mimi & Hill Design",
		city: "Westfield",
		image: require("../assets/images/Mimi.png"),
		rating: "4.0",
		ingredients: ["Wide, accessible entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "2/5",
		color: "#006A4E",
		description:
			"A comprehensive approach where a single team manages both the design and construction phases of a project.",
		interior: ["Interior spaced out and built to ADA standards"],
		parking: ["Lot #1 closest lot, still far away"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "132",
		categoryId: "07",
		name: "NosVino",
		city: "Westfield",
		image: require("../assets/images/nos.png"),
		rating: "4.0",
		ingredients: ["No steps, adequate room for wheelchair"],
		time: "5/5",
		difficulty: "4/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Neighborhood Wine Shop specializing in small production and family owned estate wineries, craft beer and spirits with an emphasis on quality and value.",
		interior: ["Spacious Interior"],
		parking: ["Street parking nearby, no accessible parking nearby"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "133",
		categoryId: "07",
		name: "T-Mobile",
		city: "Westfield",
		image: require("../assets/images/T.png"),
		rating: "4.7",
		ingredients: ["Step in front of it, have to go to the side"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Step in front of it, have to go to the side",
		interior: ["Spacious Interior"],
		parking: ["Lot #5 across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "134",
		categoryId: "07",
		name: "The Device Shop",
		city: "Westfield",
		image: require("../assets/images/TheDevice.png"),
		rating: "4.3",
		ingredients: ["Wheelchair-accessible door, wheelchair miniramp to the left"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"The Device Shop is dedicated to providing the best customer service and computer repair available to you.",
		interior: ["Spacious Interior"],
		parking: ["None nearby, Lot #1 is closest option"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "135",
		categoryId: "07",
		name: "UPS Store",
		city: "Westfield",
		image: require("../assets/images/ups.png"),
		rating: "4.7",
		ingredients: ["Good door with wheelchair miniramp to the left"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Store offering shipping, packaging, printing & other services, plus office supplies.",
		interior: ["Slightly crammed interior"],
		parking: ["No accessible parking nearby, only street parking"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✗ No Place to sit down to rest",
	},
	{
		id: "136",
		categoryId: "07",
		name: "Verizon",
		city: "Westfield",
		image: require("../assets/images/verizon.png"),
		rating: "5.0",
		ingredients: ["All good, ramp in front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Telecommunications store offering cell phones, wireless plans, accessories & more.",
		interior: ["Wide Interior"],
		parking: ["Wheelchair accessible parking lot"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "137",
		categoryId: "07",
		name: "Verizon",
		city: "Summit",
		image: require("../assets/images/verizon.png"),
		rating: "5.0",
		ingredients: ["All good, ramp in front"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Telecommunications store offering cell phones, wireless plans, accessories & more.",
		interior: ["Wide Interior"],
		parking: ["Wheelchair accessible parking lot"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
];
